@startuml diagrama_entidade_relacionamento

entity Ativo {
  *id_ativo: int <<PK>>
  --
  nome: String
  marca: String
  modelo: String
  nr_serie: String
  dt_aquisicao: Date
  vl_aquisicao: double
  status: String
  id_categoria: int <<FK>>
  id_fornecedor: int <<FK>>
  id_departamento: int <<FK>>
}

entity Licenca {
  *id: int <<PK>>
  --
  nome: String
  dt_aquisicao: Date
  vl_aquisicao: double
  dt_inicio_vigencia: Date
  dt_fim_vigencia: Date
  status: String
  id_fornecedor: int <<FK>>
}

entity Categoria {
  *id: int <<PK>>
  --
  nome: String
  observacao: String
  status: String
}

entity Garantia {
  *id: int <<PK>>
  --
  descricao: String
  dt_inicio: Date
  dt_fim: Date
  observacao: String
  status: String
  id_ativo: int <<FK>>
}

entity Fornecedor {
  *id: int <<PK>>
  --
  razao_social: String
  nome_fantasia: String
  nr_cnpj: String
  nr_telefone: String
  ds_email: String
  ds_endereco: String
  nr_endereco: int
  ds_bairro: String
  ds_municipio: String
  sg_estado: String
  status: String
}

entity Prestador {
  *id: int <<PK>>
  --
  razao_social: String
  nome_fantasia: String
  nr_cnpj: String
  nr_telefone: String
  ds_email: String
  ds_endereco: String
  nr_endereco: int
  ds_bairro: String
  + ds_municipio: String
  + sg_estado: String
  + status: String
}

entity Manutencao {
  *id: int <<PK>>
  --
  tipo: String
  observacao: String
  dt_inicio: Date
  dt_fim: Date
  vl_total: double
  status: String
  id_ativo: int <<FK>>
  id_prestador: int <<FK>>
}

entity Departamento {
  *id: int <<PK>>
  --
  nome: String
  observacao: String
  status: String
  id_setor: int <<FK>>
}

entity Setor {
  *id: int <<PK>>
  --
  nome: String
  observacao: String
  status: String
  id_empresa: int <<FK>>
}

entity Empresa {
  *id: int <<PK>>
  --
  razao_social: String
  nome_fantasia: String
  nr_cnpj: String
  nr_telefone: String
  ds_email: String
  ds_endereco: String
  nr_endereco: int
  ds_bairro: String
  ds_municipio: String
  sg_estado: String
  observacao: String
  status: String
}

entity Usuario {
  *id: int <<PK>>
  --
  login: String
  senha: String
  nivel_acesso: String
  observacao: String
  status: String
  id_pessoa: int <<FK>>
}

entity Pessoa {
  *id: int <<PK>>
  --
  nome: String
  nr_cpf: String
  dt_nascimento: String
  sexo: String
  nr_telefone: String
  ds_email: String
}

Ativo ||--o{ Categoria : possui
Ativo ||--o{ Fornecedor : fornecido por
Ativo ||--o{ Garantia : possui
Ativo ||--o{ Manutencao : registra
Manutencao ||--o{ Prestador : realizada por
Ativo ||--o{ Departamento : alocado em
Empresa ||--o{ Setor : contém
Setor ||--o{ Departamento : contém
Usuario ||--o{ Pessoa : é
Licenca ||--o{ Fornecedor : fornecida por

@enduml

